{"name": "test_login_page", "status": "failed", "statusDetails": {"message": "AssertionError: The user is not logged in successfully.\nassert None\n +  where None = user_is_logged()\n +    where user_is_logged = <pages.actions.login_actions.LoginActions object at 0x000002946F465CD0>.user_is_logged", "trace": "venv\\Lib\\site-packages\\_pytest\\fixtures.py:898: in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\nfeatures\\steps\\test_login.py:31: in step_login_user_successfully\n    assert login_page.user_is_logged(), \"The user is not logged in successfully.\"\nE   AssertionError: The user is not logged in successfully.\nE   assert None\nE    +  where None = user_is_logged()\nE    +    where user_is_logged = <pages.actions.login_actions.LoginActions object at 0x000002946F465CD0>.user_is_logged"}, "description": "login.feature: Login User", "attachments": [{"name": "stdout", "source": "e31f2302-e744-41cc-955e-f5e09a36f5e0-attachment.txt", "type": "text/plain"}], "start": 1729968278644, "stop": 1729968293007, "uuid": "0c3cfb22-8b35-4928-9951-3a70f12a19ab", "historyId": "433c93b71e7cd749b8bf2a660bfa517d", "testCaseId": "433c93b71e7cd749b8bf2a660bfa517d", "fullName": "features.steps.test_login#test_login_page", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "features.steps"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "manuel"}, {"name": "thread", "value": "23444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "features.steps.test_login"}]}