{"name": "test_login_page", "status": "broken", "statusDetails": {"message": "pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Then \"The user access successfully\". Line 7 in scenario \"Register User\" in the feature \"C:\\Users\\manue\\Documents\\automation-bdd-selenium\\features\\register.feature\"", "trace": "E   pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Then \"The user access successfully\". Line 7 in scenario \"Register User\" in the feature \"C:\\Users\\manue\\Documents\\automation-bdd-selenium\\features\\register.feature\"\nAll traceback entries are hidden. Pass `--full-trace` to see hidden and internal frames."}, "description": "register.feature: Register User", "start": 1729969630707, "stop": 1729969634217, "uuid": "936e728f-be10-4891-a4ce-4466d24f04c8", "historyId": "84368c6e3c571653cd251111251e854b", "testCaseId": "84368c6e3c571653cd251111251e854b", "fullName": "features.steps.test_register#test_login_page", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "features.steps"}, {"name": "suite", "value": "test_register"}, {"name": "host", "value": "manuel"}, {"name": "thread", "value": "20516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "features.steps.test_register"}]}